// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Propel",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Propel",
            targets: ["AppModule"],
            bundleIdentifier: "Angelo.PropelWalk",
            teamIdentifier: "3VZ994N5DL",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.mint),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Propel needs camera access to detect obstacles and help you navigate your surroundings safely. All processing happens on your device  no data is sent online."),
                .motion(purposeString: "Propel needs camera access to detect obstacles and help you navigate your surroundings safely"),
                .microphone(purposeString: "Unknown Usage DescriptionPropel may use the microphone for voice commands to make the app more accessible.")
            ],
            appCategory: .healthcareFitness
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
